# Generated by Django 4.2.3 on 2023-07-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('salario_base', models.FloatField()),
                ('horas_trabajadas', models.IntegerField()),
                ('activo', models.BooleanField(default=True, editable=False)),
            ],
        ),
    ]
